# Generated by Django 3.1 on 2020-08-15 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                 serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254,
                 null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tourprogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                 serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254,
                 null=True)),
                ('tourname', models.CharField(max_length=254)),
                ('region', models.CharField(max_length=254)),
                ('maximum', models.CharField(max_length=254)),
                ('price_adult', models.DecimalField(decimal_places=2,
                 max_digits=6)),
                ('price_child', models.DecimalField(decimal_places=2,
                 max_digits=6)),
                ('departure_date', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(blank=True, decimal_places=2,
                 max_digits=6, null=True)),
                ('included', models.CharField(blank=True, max_length=254,
                 null=True)),
                ('not_included', models.CharField(blank=True, max_length=254,
                 null=True)),
                ('meeting_place', models.CharField(max_length=254)),
                ('image_url', models.URLField(blank=True, max_length=1024,
                 null=True)),
                ('image', models.ImageField(blank=True, null=True,
                 upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL,
                 to='tourprograms.category')),
            ],
        ),
    ]
