# Generated by Django 3.1 on 2020-08-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourprograms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourprogram',
            name='estimated_times',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tourprogram',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourprogram',
            name='price_adult',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tourprogram',
            name='price_child',
            field=models.IntegerField(),
        ),
    ]
