# Generated by Django 3.1 on 2020-08-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourprograms', '0002_auto_20200815_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourprogram',
            old_name='tourname',
            new_name='name',
        ),
    ]
