# Generated by Django 3.1 on 2020-08-15 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourprograms', '0003_auto_20200815_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
