# Generated by Django 3.1 on 2020-08-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourprograms', '0004_auto_20200815_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourprogram',
            old_name='price_adult',
            new_name='priceadult',
        ),
        migrations.RenameField(
            model_name='tourprogram',
            old_name='price_child',
            new_name='pricechild',
        ),
    ]
