# Generated by Django 3.1 on 2020-08-21 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tourprograms', '0005_auto_20200815_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourprogram',
            name='date',
            field=models.DateTimeField(auto_now_add=True,
                                       default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
