# Generated by Django 3.1 on 2020-08-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourprograms', '0006_tourprogram_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourprogram',
            name='maximum',
            field=models.IntegerField(),
        ),
    ]
