# Generated by Django 3.1 on 2020-08-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourprograms', '0008_auto_20200823_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourprogram',
            name='date',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
